#pragma once

#define INIT_FUNCTION_NAME      __slimgpu_init
#define GETTID_FUNCTION_NAME    __slimgpu_gettid
#define STORE_OP_FUNCTION_NAME  __slimgpu_log
#define DEVICE_AREA_GLOBAL_NAME __slimgpu_dev_area

#define NAMEOF2(x) #x
#define NAMEOF(x) NAMEOF2(x)

#define NAMEOF_INIT_FUNCTION_NAME	   NAMEOF(INIT_FUNCTION_NAME)
#define NAMEOF_GETTID_FUNCTION_NAME    NAMEOF(GETTID_FUNCTION_NAME)
#define NAMEOF_LOG_OP_FUNCTION_NAME  NAMEOF(STORE_OP_FUNCTION_NAME)
#define NAMEOF_DEVICE_AREA_GLOBAL_NAME NAMEOF(DEVICE_AREA_GLOBAL_NAME)
